@Warehouse.Api_HostAddress = https://localhost:7054

### Login
POST {{Warehouse.Api_HostAddress}}/api/authentication/login
accept: */*
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###Logout
POST {{Warehouse.Api_HostAddress}}/api/authentication/logout
accept: */*
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0yMjIyLTIzMjEtMjMyMS0xMTExMTExMTE0NTYiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6IjJjYzEwMjc0LTQxMWEtNDQ5OC1iMzZkLWRlNjU5ZGZlMWM2OSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTM1ODU3MywiaXNzIjoiRGlnaXRhbGxXYXJlaG91c2UiLCJhdWQiOiJEaWdpdGFsbFdhcmVob3VzZSJ9.JOkbx6wltY-NYdBSe7i9QwZ9XlkR_z27rPUT6wpderM",
  "refreshToken": "c6kmGN8pNe0AcnsRSIVAlPE5GOcxDbxv0jRo3pT5ogxlCzCOJ0GxvcoBWoZHm7wbdip+HrGd1eP6p1V27gPBWQ=="
}

### Refresh
POST {{Warehouse.Api_HostAddress}}/api/authentication/refresh
accept: */*
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0yMjIyLTIzMjEtMjMyMS0xMTExMTExMTE0NTYiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6ImIzMGY1M2M1LTJlYjQtNDE5OS05MDE3LTUzYzlhNDhlMGM2NCIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTExODQyMCwiaXNzIjoiRGlnaXRhbGxXYXJlaG91c2UiLCJhdWQiOiJEaWdpdGFsbFdhcmVob3VzZSJ9.cixKrz8nE3XVo87Vf9vgxNWUQ_YO4ZUwYFXiGJ4wEcw",
  "refreshToken": "wZqFQsdTSTBi7m0HbJ+Or2c1dxK3OwTObSWdnzAcux8akVEKenwD/PLaWmR7VPMtnh1Z4FENniYh1KK8Ekb0AQ=="
}


### Get All Products
GET {{Warehouse.Api_HostAddress}}/api/products
accept:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0yMjIyLTIzMjEtMjMyMS0xMTExMTExMTE0NTYiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6ImViYzY2NTY3LWYyZjItNDBhOS04NDM5LTBmMjc1ZDRmM2MzYSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTM2MDU4NCwiaXNzIjoiRGlnaXRhbGxXYXJlaG91c2UiLCJhdWQiOiJEaWdpdGFsbFdhcmVob3VzZSJ9.IMma6NkWU7uz3ptRApYdtnIRG58Fr6MLNTLalDebJ1c