@Warehouse.Api_HostAddress = https://localhost:7054

### Login
POST {{Warehouse.Api_HostAddress}}/api/authentication/login
accept: */*
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###Logout
POST {{Warehouse.Api_HostAddress}}/api/authentication/logout
accept: */*
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0yMjIyLTIzMjEtMjMyMS0xMTExMTExMTE0NTYiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6IjY3MjY5NmViLWNhMGUtNDI5Ni05N2VlLTc5YmM4MGRiNDMyOCIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTM4NDM3NiwiaXNzIjoiRGlnaXRhbGxXYXJlaG91c2UiLCJhdWQiOiJEaWdpdGFsbFdhcmVob3VzZSJ9.MbdKqsLy9bJ02Gh7Ru1QqEw8ijP5oR_sOf53iE-Hnms",
  "refreshToken": "Mdw+Mc8DYw9JZ1t7FUwYHx48eJtY5AaDRy9notXSt9olneI0rlkTKD7IAygNsZnsQvBKplYLBqWJFa2fKxxuFA=="
}

### Refresh
POST {{Warehouse.Api_HostAddress}}/api/authentication/refresh
accept: */*
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0yMjIyLTIzMjEtMjMyMS0xMTExMTExMTE0NTYiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6ImIzMGY1M2M1LTJlYjQtNDE5OS05MDE3LTUzYzlhNDhlMGM2NCIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTExODQyMCwiaXNzIjoiRGlnaXRhbGxXYXJlaG91c2UiLCJhdWQiOiJEaWdpdGFsbFdhcmVob3VzZSJ9.cixKrz8nE3XVo87Vf9vgxNWUQ_YO4ZUwYFXiGJ4wEcw",
  "refreshToken": "wZqFQsdTSTBi7m0HbJ+Or2c1dxK3OwTObSWdnzAcux8akVEKenwD/PLaWmR7VPMtnh1Z4FENniYh1KK8Ekb0AQ=="
}


### Get All Products
GET {{Warehouse.Api_HostAddress}}/api/products
accept:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0yMjIyLTIzMjEtMjMyMS0xMTExMTExMTE0NTYiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6IjIwODliMjE3LTNkZTEtNDEwZC1hYzA1LWM4N2MwZWI2YmQ1MSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTM4NDA4NSwiaXNzIjoiRGlnaXRhbGxXYXJlaG91c2UiLCJhdWQiOiJEaWdpdGFsbFdhcmVob3VzZSJ9.-MzWl6yM2MqcFpvdizeTQthaoXIXQ-uEfVfk-pX2yWcjItNDBhOS04NDM5LTBmMjc1ZDRmM2MzYSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTM2MDU4NCwiaXNzIjoiRGlnaXRhbGxXYXJlaG91c2UiLCJhdWQiOiJEaWdpdGFsbFdhcmVob3VzZSJ9.IMma6NkWU7uz3ptRApYdtnIRG58Fr6MLNTLalDebJ1c